services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - db_redis:/root/redis
      - db_redis:/data
    command: redis-server --dir /data --save 60 1
    networks:
      - app_backend
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile_tg_bot
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - env/tg_bot.env
    volumes:
      - $PWD:/usr/src/app
    networks:
      - app_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    env_file:
      - env/app.env
      - env/db.env
    networks:
      - app_backend
    volumes:
      - $PWD:/usr/src/app # hot reloading?
    restart: always
    ports:
      - 8445:8443
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://127.0.0.1:8445/webhook/healthcheck || curl -kfs https://127.0.0.1:8445/webhook/healthcheck" ]
      interval: 2s
      timeout: 5s
      retries: 15
      start_period: 5s
    depends_on:
      redis:
        condition: service_healthy


volumes:
  db_redis:
    name: db_redis
    driver: local

networks:
  app_backend: